### ISSUE TITLE
Hotreloading breaks when require path contains slashes?

### ISSUE THREAD

**Issue by pdesaulniers** [rxi/lurker#12]
If I require a file called `src/background.lua` like this:
```lua
local background = require("src/background")
```

...then, lurker detects the change:
```
[lurker] Hotswapping 'src/background.lua'...
[lurker] Swapped 'src/background.lua' in 0.00023200000000001 secs
```
However, the hotreload has no effect.

If I change the slash in the path to a period:
```lua
local background = require("src.background")
```
then, background.lua is reloaded correctly on save.

**Comment by rxi** [comment]
Slashes shouldn't typically be used when passing a string to `require`, lua replaces `.` with the platform-specific directory separator.

**Comment by pdesaulniers** [comment]
Indeed, using the `.` seems like best practice. Still, the console output seemed to indicate that the hot-swap was working, so I was a bit confused.

Furthermore, it seems like the hot-swap can break if we set a custom require path:
```lua
love.filesystem.setRequirePath("src/?.lua;")
local background = require("background")
```
I'm not sure if that's because the path contains a slash.

(Note that I don't mind using `.` and avoiding setRequirePath, I'm just reporting this in case it's useful)
